spring.application.name=ai-integration-backend
server.port=8070
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

api.key=${API_KEY}
base-url=https://openrouter.ai/api/v1
model=google/gemma-4-26b-a4b-it:free
